databases:
  - name: churchappapi
    databaseName: churchappapi
    user: churchappapi

services:
  - type: web
    name: churchappapi
    runtime: ruby
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: churchappapi
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true